name: Continuous Integration

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 15.x
        uses: actions/setup-node@master
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: npm install && npm run bootstrap

      - name: Run tests
        run: npm run "test:all"
        env:
          CI: true

      - name: Run builds
        run: npm run build