name: Continous Delivery

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 15.x
        uses: actions/setup-node@master
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: npm install && npm run bootstrap

      - name: >
          Releases packages if new versions detected
          or create pull request with new versions if changesets detected
        uses: changesets/action@master
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}